# Generated by Django 3.2.6 on 2025-10-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0004_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
